### ISSUE TITLE
Unable to parse zfs volume name while running 

### ISSUE THREAD

**Issue by advisorgee** [modem7/public_scripts#3]
Sorry hit enter before I finished typing my issue. 

I get the above error when trying to use the script. It occurs in this line of the script:
qm set $VMID --scsihw virtio-scsi-single --scsi0 $DISK_STOR:$VMID/vm-$VMID-disk-0.qcow2,cache=writethrough,discard=on,iothread=1,ssd=1

I can see the volume listed in the storage, but the format is listed as raw and not qcow2
![proxmox](https://github.com/modem7/public_scripts/assets/5341449/2b6cb915-3d9b-44c8-8466-1b657ca79609)

**Comment by modem7** [comment]
Are you able to share your variables at all?

**Comment by advisorgee** [comment]
# Image variables
OSNAME="Ubuntu 22.04"
TEMPL_NAME_DEFAULT="ubuntu2204-cloud-master"
VMID_DEFAULT="900"
CLOUD_USER_DEFAULT="root"
GENPASS=$(date +%s | sha256sum | base64 | head -c 16 ; echo)
CLOUD_PASSWORD_DEFAULT=$GENPASS
MEM="2048"
BALLOON="768"
DISK_SIZE="15G"
DISK_STOR="VMData"
NET_BRIDGE="vmbr1"
VLAN="" # Set if you have VLAN requirements
QUEUES="2"
CORES="2"
OS_TYPE="l26"
AGENT_ENABLE="1" #change to 0 if you don't want the guest agent
FSTRIM="1"
BIOS="ovmf" # Choose between ovmf or seabios
MACHINE="q35"
VIRTPKG="qemu-guest-agent,cloud-utils,cloud-guest-utils"
TZ="America/Toronto"
SSHKEY="my ssh key" #Unset if you don't want to use this. Use the public key.
SETX11="yes" # "yes" or "no" required
X11LAYOUT="gb"
X11MODEL="pc105"
LOCALLANG="en_GB.UTF-8"

**Comment by modem7** [comment]
I'm also now seeing this error (I was running LVM before, and haven't needed to run the script since upgrading to ZFS). 

I'll have to investigate this further to see how to resolve.

**Comment by modem7** [comment]
@advisorgee - I've just made an initial change in https://github.com/modem7/public_scripts/commit/a8aa144877d56bd693cdeea9093af07b31b51eab - could you check if it works as expected?

https://github.com/modem7/public_scripts/blob/master/Bash/Proxmox%20Scripts/create-jammy-cloud-template.sh

**Comment by advisorgee** [comment]
that worked; I think there is this comment at the end:

"shrinking disks is not supported"

I'm not sure if that matters or not.

**Comment by modem7** [comment]
Where are you getting that message? I'm not seeing it during my tests.

I've also updated the script, so it's somewhat cleaner in https://github.com/modem7/public_scripts/commit/22d6201b137dfa0dbc3b338f2bf16a1724be5d04.

**Comment by advisorgee** [comment]
I'll test the new version

It comes in as the second last line:

update VM 900: -sshkeys <redacted>
removed '/tmp/sshkey.CwR.pub'
shrinking disks is not supported
Image not deleted

**Comment by modem7** [comment]
I'm unable to replicate that message, unfortunately. 

I've made a couple more modifications, but otherwise, it should be working as expected.

**Comment by advisorgee** [comment]
I used the new version of the script and that message no longer appears. 

Thanks for the awesome script and the quick fixes.
