### ISSUE TITLE
400 Parameter verification failed.

### ISSUE THREAD

**Issue by rossdargan** [modem7/public_scripts#4]
The script gives the following error if you don't use a ZFS store:

```
update VM 52000: -scsi0 backup-nfs:52000/vm-52000-disk-0.qcow2,cache=writethrough,discard=on,iothread=1,ssd=1 -scsihw virtio-scsi-single
400 Parameter verification failed.
vmid: type check ('integer') failed - got ''
qm set <vmid> [OPTIONS]
update VM 52000: -tags template
```

Looking at the script I'm sure it's this line causing the issue: https://github.com/modem7/public_scripts/blob/2fd0f32cdb72c1d39cde991e84822d54da52fcad/Bash/Proxmox%20Scripts/create-ubuntu-cloud-template.sh#L312

I can't figure out what that line is meant to do as nothing appears to set "$VM", and no params are passed in anyway!

Also, is there any reason it doesn't create a template as part of the script?

**Comment by modem7** [comment]
Good catch. 

I've updated the script in https://github.com/modem7/public_scripts/commit/4a6d529359051108f5880f2d5fa4db9dbe56f505 - could you see if this resolves?

> Also, is there any reason it doesn't create a template as part of the script?

My reasoning for this is that just the OS by itself doesn't make for an overly useful template. I usually create a VM using the script, then modify/add additional things (see https://flatnotes.modem7.com/note/VM-Ubuntu-Desktop-Cloud-Master) to it before I make it into a template.

**Comment by rossdargan** [comment]
![image](https://github.com/modem7/public_scripts/assets/1276400/f93565f4-cf70-487a-a9bb-a1a88fcdb28d)
This is what it created - not sure the EFI disk makes sense? 

What does this disk do?

**Comment by modem7** [comment]
The EFI disk is required for OVMF/UEFI, but it doesn't strictly need to be qcow2 with non-zfs I don't think, not that it hurts if it is.

Does it work however? Are you getting any issues or errors?

**Comment by rossdargan** [comment]
This appears to resolve my issue! Thanks!
